### ISSUE TITLE
SEO content appears to not persist in DB

### ISSUE THREAD

**Issue by crim3hound** [AppoloDev/bolt-seo#5] opened 2020-11-27 06:16 UTC
First of all, thank you for porting this extension to Bolt 4! Great work! However, it appears that the content is not being saved to the database. Not sure what the issue could be. Can you advise?

**Comment by Fredxd** [comment] 2020-11-27 10:33
Hi
Do you have check in bolt_field_translation table if you have something ?
In your developer console do you have any errors?

Thanks for feedback

**Comment by Thibault-Mantalo** [comment] 2020-11-30 08:11
HI,
Thank you very much for the work done!
Indeed, I have the same technical problem.
No errors on the logs / debug side.

I haven't had time to look in more detail yet.
But it's as if auto-mapping doesn't work with synfony ORM.

I will keep you posted if I find a solution.

_PS : sorry for my english, i'm french._

**Comment by Fredxd** [comment] 2020-11-30 08:17
> HI,
> Thank you very much for the work done!
> Indeed, I have the same technical problem.
> No errors on the logs / debug side.
> 
> I haven't had time to look in more detail yet.
> But it's as if auto-mapping doesn't work with synfony ORM.
> 
> I will keep you posted if I find a solution.
> 
> _PS : sorry for my english, i'm french._

Hi,

Actually only single hidden field is use to store data. Data is stored in stringify JSON, and provide by others SEO fields or content fields depending configuration (title, payload....)
So you can check if you have any value in this single field. Sorry i am not on it so i can't tell you it's name.
Or you can check if JS file is correctly loaded.
 
PS: Ahah no problem i am french too ;)

**Comment by Fredxd** [comment] 2020-12-24 13:31
Hi Guys, 
Still here ?

**Comment by Thibault-Mantalo** [comment] 2020-12-24 13:38
Hi,
yes still there.
 I have to look into it in January

**Comment by Fredxd** [comment] 2020-12-24 13:40
@Thibault-Mantalo Ok let me know if you see something.
I can't reproduce it and it seems to work in some users

**Comment by crim3hound** [comment] 2020-12-24 20:02
Still here. Sorry, I've been held up as well, but I was also trying to see what could be causing the issue. Will update if I find anything after the holidays.

**Comment by crim3hound** [comment] 2021-01-14 04:18
Hi @Fredxd. I have tried to look at the SEO extension, and I have seen this hidden input field `<input type="hidden" name="fields[seo]" id="field-seo" value="">`. I assume this is what you were talking about where SEO input is stored in stringified JSON? If so, it appears that no data is saved to it.

The `seo.js` file seems to load correctly; unless there is another JS file that needs to be loaded? Could you help to confirm where and how (which file) exactly the SEO data is saved to the hidden input? I also noted that if I manually input a value to `fields[seo]` via element inspector, it persists even on reload, which leads me to think that is where the issue might be?

**Comment by Fredxd** [comment] 2021-01-14 09:32
Hi @crim3hound. I think seo.js file is incomplete, i have issue now on my dev stack but i have loose my local history.
I will try to do this but i don't know when.
If someone want try to do it, it miss this:

- in **changeTarget** function add in hidden field a JSON with seo inputs data
- on **init** function keep JSON data instead of defaultsData

**Comment by Fredxd** [comment] 2021-01-14 10:18
I have do some adjustments on develop branch.
Can you try it and tell me if it's better ?

**Comment by crim3hound** [comment] 2021-01-15 06:28
Thanks @Fredxd. Let me check it out.

**Comment by crim3hound** [comment] 2021-01-15 09:55
Hey @Fredxd. I made the changes you have on your develop branch, and right now there is a `json_decode` syntax error. Can you advise?

![Screenshot 2021-01-15 124813](https://user-images.githubusercontent.com/29301735/104710247-ee1f2f80-5730-11eb-9e06-5a6f624f2aec.jpg)

**Comment by Fredxd** [comment] 2021-01-15 11:24
@crim3hound Should be fixed ;)

**Comment by crim3hound** [comment] 2021-01-15 11:31
Confirmed. Thanks for the great work, @Fredxd!

**Comment by crim3hound** [comment] 2021-01-15 11:32
Will you push a release so users can update via composer?

**Comment by Fredxd** [comment] 2021-01-15 11:33
Great ! Thanks for feedback
i will do a release in few minutes

I close this issue, if you have any problem you can open a new issue, or if you want improve it, feel to free to create a PR ;)

**Closed by Fredxd** 2021-01-15 11:33 UTC

**Comment by Fredxd** [comment] 2021-01-15 11:36
I have tag to 1.0.2 ;)

**Comment by Thibault-Mantalo** [comment] 2021-01-18 14:05
Hi !

I confirm that I just tested on my side and it works too.

**Thank you for your work !**
